### ISSUE TITLE
请问服务端与客户端的部分参数具体是做什么的（例如： -e -m）？

### ISSUE THREAD

**Issue by ghost** [libraries/daze#10]
根据我的经验猜测，
### -e string
**server -e** 是加密方式？
**client -e** 是加密方式？
> ashe, asheshadow 两者的主要区别是什么？

### -m string
**server -m** 是混淆？
> 该参数的使用方式是什么？

### -f string
**client -f** 是过滤规则？
> auto, none, ipcn 是不是分别指的是：自动判断是否走代理，全局(全不走代理，不做判断)，大陆IP地址不走代理。

对了，还有客户端指定 DNS 的主要作用是什么？是使用 -f 参数，当目标网站不走代理时，通过该 DNS 获取域名解析吗？

希望可以告诉我我猜测的是否正确，指出哪里存在错误，并且解开我的疑惑。👌

**Comment by mohanson** [comment]
-e: 客户端与服务端的加密方式. 客户端与服务端必须相同. -e ashe 做了数据加密, -e asheshadow 做了数据加密和混淆; 如果使用 -e asheshadow, 服务端对外表现为一个标准的 http 网站.
-m: 混淆站的地址. 当使用 -e asheshadow 时, 服务端会转发所有 http 流量到目标站点.
-k: 密钥. 服务端和客户端使用的密钥必须相同才能正常建立连接.

-f:过滤规则. auto 表示自动判断流量是否需要代理(程序会实现使用本地网路连接目标地址, 如果 4 s 内发现无法建立连接 则转而使用代理. 相关规则会被保留, 因此只在第一次连接时速度较慢, 之后正常), none 表示除本地流量外的所有流量均走代理, ipcn 表示非中国大陆地区的全部流量走代理.

**Comment by ghost** [comment]
好的，感谢解答。

**Comment by ghost** [comment]
突然想起来，你还没有回复我客户端指定 DNS 的主要作用是什么。。。😂

另外，我提一个建议：
> 当前的 HTTP 混淆链接，在外界看来是在访问 `ip:端口` 这样的地址，有没有可能实现显示为 `域名:端口` 这样？
> 可能需要自己有个域名，并指向代理服务器。
> 而客户端或者服务端如何如何配置后，就在外界看来我们访问的是 `域名:端口` 这样的，而不是访问的IP，毕竟相对于 IP ，域名方式混淆更完美。
> 最好是只能通过该域名访问，不能通过IP或者随便一个域名访问，这样子混淆效果更好。

**Comment by mohanson** [comment]
1) 客户端指定 dns 作用: 从域名解析为 IP 地址, 然后便可以根据 IP 判断 IP 是否从属于中国大陆. 

2) 可以的. 将 daze server -l 0.0.0.0:80 绑定到 80 端口, 然后将域名 ANAME 到 IP 地址即可. 这样外界看来 daze server 只表现为一个 http 网站.

3) 可以只通过域名访问. 比如你有一个 a.com 的域名, 使用 `daze server -l a.com:80 -e asheshadow` 即可实现只能通过域名访问.

**Comment by ghost** [comment]
1. 理解了，这样被DNS污染的IP解析到的都是海外的污染IP，而正常域名也能解析分辨国内外。

2. 我测试的确可行，不过要解析为IP地址，需要是 `A` 记录类型（CNAME记录类型只能指向域名）。

3. 这个我测试不通过，即当我通过 `-l a.com:80` 方式启动服务端时，浏览器无论是通过 `IP:80` 还是 `a.com:80` 还是其他任意域名(hosts 指向IP)，只要是访问该服务器 `80` 端口的，都会指向 daze 的HTTP反向代理网站。

**Comment by mohanson** [comment]
3) 测试后确实不可行, 通过 IP 还是可以访问. 未来考虑添加该功能.

**Comment by ghost** [comment]
在写教程前，我还有个问题。
就是上面你说的 2. XXX 。

> 当我将域名解析到代理IP时，我客户端使用 `-s a.com:80` 时，当加密方式是 `asheshadow` 时，对外界确定是模拟访问的 `a.com:80` 吗？因为我也看不到在外界我的流量数据是怎么样的。
> 
> 客户端链接的远程服务器地址是域名时（加密方式为 `asheshadow` ），客户端是把域名解析为IP后，直接链接该IP，还是携带HOST域名信息模拟访问 `a.com:80` ?

我因为自己看不到具体流量表现为什么，所以想跟你确认一下。

**Comment by mohanson** [comment]
1) 是的, 流量会伪装成 a.com:80 的 HTTP 请求.
2) fq 流量携带 Host 信息, 模拟成一个标准 HTTP 请求访问 a.com:80

**Comment by ghost** [comment]
教程写完了，你看看教程里有没有错误或者漏掉的：

- [DAZE 轻量化代理软件 —— Windows 客户端简单使用教程](https://doub.io/daze-jc2/)
- [一个由Go语言编写的轻量化代理工具 —— DAZE 服务端手动教程](https://doub.io/daze-jc1/)

**Comment by mohanson** [comment]
太棒了, 比我本人写的都详细~
