### ISSUE TITLE
疑似存在 DNS 泄露问题

### ISSUE THREAD

**Issue by ghost** [libraries/daze#12]
有个人发现了这个问题并告诉了我，我测试了下。

当我直连访问时，显示的是中国DNS。
当我使用 DAZE 的 `-f none` 访问时，显示的还是中国DNS。
而我使用其他的代理软件访问时，则是代理服务器的DNS。

我也不清楚具体原理什么的，只是告诉一下作者，看一看是哪里的问题，希望尽快修复。

[DNS泄露 测试网站](https://www.dnsleaktest.com/results.html)

**Comment by mohanson** [comment]
我了解了, 我会研究下 ss 对该问题的处理方式.
