### ISSUE TITLE
udp的实现有点奇怪

### ISSUE THREAD

**Issue by xxxsen** [libraries/daze#13]
看代码。。对udp的处理逻辑跟tcp一样都是传给远端去处理了, 但是本地并没有监听一个udp端口供被代理端来发包？ 看了socks5的介绍。。udp流量应该不是通过握手建立的tcp链接来的吧？

**Comment by mohanson** [comment]
谢谢指正! 我重新阅读了 rfc 文档, 是我的实现错了.
