### ISSUE TITLE
无法访问HTTPS网址？

### ISSUE THREAD

**Issue by silkriver** [libraries/daze#28]
使用代理后发现访问HTTPS网址会报错？需要什么额外的操作吗

**Comment by mohanson** [comment]
请提供更多信息，包括启动命令，日志等

**Comment by silkriver** [comment]
按说明中服务端 daze server -l 0.0.0.0:61419
客户端 daze client -s SERVER:61419 -l 127.0.0.1:61420 -dns 114.114.114.114:53
设置代理 socks v5 127.0.0.1:61420
浏览器显示建立安全连接失败 连接到 www.google.com 时发生错误。PR_END_OF_FILE_ERROR
日志显示 2019/11/01 10:16:28 Connect[socks5] www.google.com:443

daze cmd curl https://google.com --proxy 127.0.0.1:61420
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed
2019/11/01 10:31:35 exit status 35

**Comment by mohanson** [comment]
请检查一下你服务器与 pc 的时间是否一致。daze 在协议中加入了加密的 timestamp 检查并且强制要求服务端时间与请求中的时间差值在 120 秒以内。

**Comment by silkriver** [comment]
谢谢，原来是这样

更新：改时间后确实可以用了，问题解决~
