### ISSUE TITLE
这个和ss和v2r相比有什么优势?

### ISSUE THREAD

**Issue by flyhigao** [libraries/daze#30]
我简单在bandwagon上测试了下,速度比ss快些(5%~10%)
但是这个和成熟的ss和v2r相比还有什么优势?

**Comment by mohanson** [comment]
最大优势是低调啦, 人类很少主动去杀死一只蚂蚁

**Comment by flyhigao** [comment]
其实daze和ss的流量在gfw处都是显示加密未知协议,这些流量会导入专门设备进一步分析.
之前ss和v2r的流量特征(不是包特征)已经被神经网络学习了. daze用的人多后, 也会被相同算法进行学习的. 
建议得有自己的独特优势.

**Comment by mohanson** [comment]
daze 现在自带两个协议, 一个是 protocal/ashe, 一个是 protocal/asheshadow, 其中后者是伪装成明文 http 协议进行通信.

同时我已经考虑到你说的被针对性识别的问题, 因此在代码层面上我预先定义好了协议接口, 使用者 clone 下来可以很方便的在上面写自己的私有协议, 比如可以仿照 https://github.com/mohanson/daze/blob/master/protocol/ashe/engine.go 去修改. 因为目前没有被针对, 所以现在已有的两个协议还是安全的.

**Comment by flyhigao** [comment]
哦,我看了asheshadow ,这个很好.避免了被主动探测,不用去部署缓慢的tls和ws .

有关避免神经网络学习的建议是, 是否可以增加选项, 如果打开就:
1  动态更改流量中包的大小,不要每次都是固定大小,可以在500~1400之间
2  在流量序列中插入随机无效的包. 
3  ...
这样让训练模型永远也无法收敛.

**Comment by mohanson** [comment]
我并不想走你上面说的几种方法的老路, 这条路很多前辈都走了, 但基本都是失败的. 我认为最优的解决办法不是 "隐藏自己", 而是 "欺骗别人".

比如: 
- 伪装成迅雷下载的协议? 毕竟这个很常见, 而且下载的文件都是乱七八糟的
- 伪装成 ftp 协议? 这个曾在我的 TODO List 中, 但因为已有的协议一直没出问题所以没提上日程
- 伪装成 baidu 爬虫? 度娘有通往国外网站的流量很正常

这些想法的优点是它们不是 "无法识别" 的流量. 随便说说.

**Comment by flyhigao** [comment]
我开发ids好几年,也学习过神经网络.
我并不是要隐藏自己,而是建议想办法让训练算法无法收敛.

另外,如果要模拟成其他的协议, 这才是最大的特征,反而容易被检出.
