### ISSUE TITLE
和其他主流软件相比,延迟过大

### ISSUE THREAD

**Issue by flyhigao** [libraries/daze#31]
测试环境: aliyun国际 新加坡服务器
测试软件: 
1 v2ray 4.21.3 (h2 over tls1.2)
2 daze v1.13
测试命令:curl --insecure -kvx 127.0.0.1:1089 -w %{time_namelookup}::%{time_connect}::%{time_starttransfer}  https://www.google.com/humans.txt

多次测试1的结果是200ms左右, 而daze的结果是300ms左右
二者配置中都开了绕过cnip.

**Comment by mohanson** [comment]
试下
 
```sh
$ curl --socks4a 127.0.0.1:1089 -kv -w %{time_namelookup}::%{time_connect}::%{time_starttransfer} https://www.google.com/humans.txt
```

在有些人的测试下, daze 性能会更优: https://github.com/mohanson/daze/issues/30#issue-518299068

**Comment by flyhigao** [comment]
那个issue是我以前发的，那是测流量，今天才测试延迟。

**Comment by mohanson** [comment]
哈哈, 其实你说会有延迟问题我也有点奇怪, 估计最大可能是出现在 dns 这块, daze 没有使用操作系统的 dns 而是使用的 golang 标准库中的纯 go 实现的 dns, 性能会差一点, 我试了下直接 ip 访问 google 会有提升.
