### ISSUE TITLE
rule文件问题

### ISSUE THREAD

**Issue by ghost** [libraries/daze#39]
支不支持 
192.169.1.0/24
这种形式?

**Comment by mohanson** [comment]
不支持. [保留地址](https://zh.wikipedia.org/wiki/保留IP地址) 目前已经被硬编码在代码中, 只能走本地网络(除非在 rule 中再次被指定

https://github.com/mohanson/daze/blob/master/daze.go#L94

但是你可以在 rule 文件中使用 glob 语法, 以下语法等价 `192.169.1.0/24`

```
192.169.1.*
```

**Comment by ghost** [comment]
好的 谢谢回复
