### ISSUE TITLE
作者有木有打算编译二进制可执行文件发布到 releases ？

### ISSUE THREAD

**Issue by ghost** [libraries/daze#9]
目前如果要用 Daze 的话，还需要安装 Go 环境，如果想让更多人使用，就不太方便了。
希望可以定个版本号，持续发布编译后的二进制可执行文件到 releases。
到时候我会测试测试代理效果，考虑写一些 Daze 教程介绍给大家。

—— [逗比根据地](https://doub.io)

**Comment by ghost** [comment]
虽然我还没测试代理效果如何，但是作为一个代理软件，不能让大家广泛使用岂不是很可惜😔。。。
毕竟是让大家一起用，不仅能提供新建议、及时反馈BUG，能帮助到他人身为作者应该也会开心吧~😀

Github 上开源的代理软件有很多，但是大部分都不出名，很多代理软件都是靠他人推荐而得知的。
我知道你这个代理软件，也是有个人在我[网站推荐](https://doub.io/guestbook/comment-page-33/#comment-44314)给我的。

不过，如果你真的不想让该代理软件广泛传播，那么我也会尊重你的选择。👍

**Comment by mohanson** [comment]
我阅读了你写的几篇文章, 我想, 如果你觉得合适的话你可以写一些文章. 文章中请不要包含任何关于
1) 商用, 收费, 多人组队等内容. 
2) 敏感内容. 

谢谢.

**Comment by ghost** [comment]
### 1. 商用, 收费, 多人组队等内容.
我写文章自然是扯不上这些的，我只会去写该代理软件的使用教程，至于他人怎么去使用我就管不到了。

当然，我看了下你的代理软件，基本上只适用于个人使用，不适用于商用，商用还是 SS SSR V2ray 这类支持多用户数据库管理的。
而且一旦支持多用户数据库管理，除了增加作者工作量以外，还会引起GFW的重点关注，得不偿失，既得利益者反而是那些开机场的。

### 2. 敏感内容.
这个敏感内容指的是什么？

**Comment by mohanson** [comment]
2. 任何涉及 zz 的内容. 我阅读你的文章发现你从不讲这些, 只是再着重提醒以下...

**Comment by ghost** [comment]
嗯，我做网站写教程纯粹是为了兴趣，对政治不感冒，所以我的文章里从来都不会涉及政治倾向言论。即使讨论 GFW ，也只说 GFW 自身，也不会去延伸到政治话题。

既然你同意了，那么我稍后会研究下 Daze ，考虑写一些教程。
